module.exports ={
	GET_EDITABLE_PRODUCT :"GET_EDITABLE_PRODUCT",
	RECEIVED_EDITABLEPRODUCT :"RECEIVED_EDITABLEPRODUCT",
	RECEIVED_PRODUCTS :"RECEIVED_PRODUCTS",
	ADD_PRODUCT:"ADD_PRODUCT",
	DELETE_PRODUCT:"DELETE_PRODUCT"
}