module.exports = {
	GET_EDITABLE_PRODUCT: "GET_EDITABLE_PRODUCT",
	RECEIVED_EDITABLEPRODUCT: "RECEIVED_EDITABLEPRODUCT",
	RECEIVED_PRODUCTS: "RECEIVED_PRODUCTS",
	SAVE_PRODUCT: "SAVE_PRODUCT",
	DELETE_PRODUCT: "DELETE_PRODUCT",
	GET_PRODUCTS: "GET_PRODUCTS",
	SAVE_SUCCESSFULLY: "SAVE_SUCCESSFULLY",
	DEFAULT_DATE_FORMAT: "YYYY-MM-DD",
	PRODUCTS_STORAGE: "PRODUCTS_STORAGE",
	PRODUCT_NOTFOUND: "PRODUCT_NOTFOUND"
}